create table if not exists public.archive_produzione (
  id bigint generated by default as identity primary key,
  dedup_key text not null unique,
  period_start date not null,
  period_end date not null,
  period_label text not null default '',
  commodity text not null,
  agente text not null,
  agent_key text not null,
  in_attivazione_count integer not null default 0,
  in_attivazione_consumo numeric not null default 0,
  consumo_totale numeric not null default 0,
  source_files text[] not null default '{}'::text[],
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists archive_produzione_period_idx on public.archive_produzione (period_start, period_end);
create index if not exists archive_produzione_commodity_idx on public.archive_produzione (commodity);
create index if not exists archive_produzione_agente_idx on public.archive_produzione (agente);
create index if not exists archive_produzione_agent_key_idx on public.archive_produzione (agent_key);

create table if not exists public.production_agent_zones (
  agent_key text primary key,
  agente text not null,
  regione text,
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists production_agent_zones_regione_idx on public.production_agent_zones (regione);
create index if not exists production_agent_zones_agente_idx on public.production_agent_zones (agente);

alter table public.archive_produzione enable row level security;
alter table public.production_agent_zones enable row level security;

grant select, insert, update, delete on table public.archive_produzione to anon, authenticated;
grant select, insert, update, delete on table public.production_agent_zones to anon, authenticated;
grant usage, select on sequence public.archive_produzione_id_seq to anon, authenticated;

drop policy if exists "archive produzione select" on public.archive_produzione;
drop policy if exists "archive produzione insert" on public.archive_produzione;
drop policy if exists "archive produzione update" on public.archive_produzione;
drop policy if exists "archive produzione delete" on public.archive_produzione;

create policy "archive produzione select"
on public.archive_produzione for select
to anon, authenticated
using (true);

create policy "archive produzione insert"
on public.archive_produzione for insert
to anon, authenticated
with check (true);

create policy "archive produzione update"
on public.archive_produzione for update
to anon, authenticated
using (true)
with check (true);

create policy "archive produzione delete"
on public.archive_produzione for delete
to anon, authenticated
using (true);

drop policy if exists "production agent zones select" on public.production_agent_zones;
drop policy if exists "production agent zones insert" on public.production_agent_zones;
drop policy if exists "production agent zones update" on public.production_agent_zones;
drop policy if exists "production agent zones delete" on public.production_agent_zones;

create policy "production agent zones select"
on public.production_agent_zones for select
to anon, authenticated
using (true);

create policy "production agent zones insert"
on public.production_agent_zones for insert
to anon, authenticated
with check (true);

create policy "production agent zones update"
on public.production_agent_zones for update
to anon, authenticated
using (true)
with check (true);

create policy "production agent zones delete"
on public.production_agent_zones for delete
to anon, authenticated
using (true);
