create table if not exists public.archive_recessi (
  id bigint generated by default as identity primary key,
  dedup_key text not null unique,
  commodity text not null default 'N/D',
  validita_date date,
  validita_text text not null default '',
  month_key text not null default '',
  agente text not null default '',
  denominazione text not null default '',
  pod_pdr text not null default '',
  tipo_cliente text not null default '',
  consumo numeric,
  raw jsonb not null default '{}'::jsonb,
  source_files text[] not null default '{}'::text[],
  source_sheets text[] not null default '{}'::text[],
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists archive_recessi_month_idx on public.archive_recessi (month_key);
create index if not exists archive_recessi_commodity_idx on public.archive_recessi (commodity);
create index if not exists archive_recessi_agente_idx on public.archive_recessi (agente);
create index if not exists archive_recessi_tipo_cliente_idx on public.archive_recessi (tipo_cliente);
create index if not exists archive_recessi_denominazione_idx on public.archive_recessi (denominazione);
create index if not exists archive_recessi_pod_pdr_idx on public.archive_recessi (pod_pdr);

alter table public.archive_recessi enable row level security;

grant select on table public.archive_recessi to anon;
grant usage, select on sequence public.archive_recessi_id_seq to anon;

drop policy if exists "archive recessi select" on public.archive_recessi;
create policy "archive recessi select"
on public.archive_recessi
for select
to anon
using (true);

create or replace function public.archive_recessi_import_rows(
  p_file_name text,
  p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  was_existing boolean;
  inserted_count integer := 0;
  duplicate_count integer := 0;
  total_count integer := 0;
  v_sheet text;
begin
  if coalesce(trim(p_file_name), '') = '' then
    raise exception 'Nome file mancante';
  end if;

  if p_rows is null or jsonb_typeof(p_rows) <> 'array' then
    raise exception 'Righe non valide';
  end if;

  for item in select value from jsonb_array_elements(p_rows)
  loop
    total_count := total_count + 1;

    select exists(
      select 1
      from public.archive_recessi
      where dedup_key = coalesce(item->>'dedup_key', '')
    ) into was_existing;

    v_sheet := coalesce(item->>'source_sheet', '');

    insert into public.archive_recessi (
      dedup_key,
      commodity,
      validita_date,
      validita_text,
      month_key,
      agente,
      denominazione,
      pod_pdr,
      tipo_cliente,
      consumo,
      raw,
      source_files,
      source_sheets,
      updated_at
    )
    values (
      coalesce(item->>'dedup_key', ''),
      coalesce(nullif(item->>'commodity', ''), 'N/D'),
      nullif(item->>'validita_date', '')::date,
      coalesce(item->>'validita_text', ''),
      coalesce(item->>'month_key', ''),
      coalesce(item->>'agente', ''),
      coalesce(item->>'denominazione', ''),
      coalesce(item->>'pod_pdr', ''),
      coalesce(item->>'tipo_cliente', ''),
      case
        when item ? 'consumo' and jsonb_typeof(item->'consumo') = 'number'
          then (item->>'consumo')::numeric
        else null
      end,
      coalesce(item->'raw', '{}'::jsonb),
      array[p_file_name],
      case when v_sheet = '' then '{}'::text[] else array[v_sheet] end,
      now()
    )
    on conflict (dedup_key) do update
    set
      commodity = case when excluded.commodity <> 'N/D' then excluded.commodity else archive_recessi.commodity end,
      validita_date = coalesce(excluded.validita_date, archive_recessi.validita_date),
      validita_text = case when excluded.validita_text <> '' then excluded.validita_text else archive_recessi.validita_text end,
      month_key = case when excluded.month_key <> '' then excluded.month_key else archive_recessi.month_key end,
      agente = case when excluded.agente <> '' then excluded.agente else archive_recessi.agente end,
      denominazione = case when excluded.denominazione <> '' then excluded.denominazione else archive_recessi.denominazione end,
      pod_pdr = case when excluded.pod_pdr <> '' then excluded.pod_pdr else archive_recessi.pod_pdr end,
      tipo_cliente = case when excluded.tipo_cliente <> '' then excluded.tipo_cliente else archive_recessi.tipo_cliente end,
      consumo = coalesce(excluded.consumo, archive_recessi.consumo),
      raw = case when excluded.raw <> '{}'::jsonb then excluded.raw else archive_recessi.raw end,
      source_files = (
        select array_agg(distinct x order by x)
        from unnest(archive_recessi.source_files || excluded.source_files) as t(x)
      ),
      source_sheets = (
        select coalesce(array_agg(distinct x order by x), '{}'::text[])
        from unnest(archive_recessi.source_sheets || excluded.source_sheets) as t(x)
        where x <> ''
      ),
      updated_at = now();

    if was_existing then
      duplicate_count := duplicate_count + 1;
    else
      inserted_count := inserted_count + 1;
    end if;
  end loop;

  return jsonb_build_object(
    'total', total_count,
    'inserted', inserted_count,
    'duplicates', duplicate_count
  );
end;
$$;

grant execute on function public.archive_recessi_import_rows(text, jsonb) to anon;

create or replace function public.archive_recessi_remove_file(
  p_file_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  touched_count integer := 0;
  deleted_count integer := 0;
begin
  update public.archive_recessi
  set
    source_files = array_remove(source_files, p_file_name),
    updated_at = now()
  where p_file_name = any(source_files);

  get diagnostics touched_count = row_count;

  delete from public.archive_recessi
  where coalesce(array_length(source_files, 1), 0) = 0;

  get diagnostics deleted_count = row_count;

  return jsonb_build_object(
    'touched', touched_count,
    'deleted', deleted_count
  );
end;
$$;

grant execute on function public.archive_recessi_remove_file(text) to anon;
