create table if not exists public.report_notification_templates (
  id bigint generated by default as identity primary key,
  admin_id bigint not null references public.admin_users(id) on delete cascade,
  name text not null,
  subject text not null default '',
  body text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint report_notification_templates_name_not_blank check (length(trim(name)) > 0),
  constraint report_notification_templates_admin_name_unique unique (admin_id, name)
);

alter table public.report_notification_templates enable row level security;
revoke all on table public.report_notification_templates from public, anon, authenticated;

create table if not exists public.report_notification_history (
  id bigint generated by default as identity primary key,
  admin_id bigint not null references public.admin_users(id) on delete cascade,
  template_id bigint null references public.report_notification_templates(id) on delete set null,
  subject text not null,
  body text not null default '',
  recipients jsonb not null default '[]'::jsonb,
  recipient_count integer not null default 0,
  success_count integer not null default 0,
  failure_count integer not null default 0,
  status text not null default 'pending',
  error text not null default '',
  sent_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint report_notification_history_counts_nonnegative check (
    recipient_count >= 0 and success_count >= 0 and failure_count >= 0
  )
);

alter table public.report_notification_history enable row level security;
revoke all on table public.report_notification_history from public, anon, authenticated;

create index if not exists report_notification_templates_admin_updated_idx
  on public.report_notification_templates(admin_id, updated_at desc);

create index if not exists report_notification_history_admin_created_idx
  on public.report_notification_history(admin_id, created_at desc);
