create table if not exists public.recruiting_hr_email_internal_config (
  id integer primary key check (id = 1),
  cron_secret text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.recruiting_hr_email_internal_config enable row level security;
revoke all on table public.recruiting_hr_email_internal_config from public, anon, authenticated;

insert into public.recruiting_hr_email_internal_config (id, cron_secret)
values (1, encode(extensions.gen_random_bytes(32), 'hex'))
on conflict (id) do nothing;

create table if not exists public.recruiting_hr_email_delivery_log (
  id bigint generated by default as identity primary key,
  admin_id bigint references public.admin_users(id) on delete cascade,
  pending_count integer not null default 0,
  status text not null default '',
  error text not null default '',
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.recruiting_hr_email_delivery_log enable row level security;
revoke all on table public.recruiting_hr_email_delivery_log from public, anon, authenticated;

select cron.schedule(
  'recruiting-hr-email-hourly',
  '0 * * * *',
  $cron$
    select net.http_post(
      url := 'https://mmjlsyonrmnhplkdxofv.supabase.co/functions/v1/recruiting-hr-email-notify',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-hr-email-cron-secret',
        (select cron_secret
           from public.recruiting_hr_email_internal_config
          where id = 1)
      ),
      body := '{"action":"cron_notify"}'::jsonb,
      timeout_milliseconds := 25000
    );
  $cron$
);
